class FolderModel {
    final int? id; // auto-generated by SQLite
    final String name; // suits of cards: Hearts, Diamonds, Spades, Clubs
    final String createdAt; // sorting as ISO string

    FolderModel({this.id, required this.name, required this.createdAt});

    Map<String, dynamic> toMap() {
        return {
            'id': id,
            'name': name,
            'created_at': createdAt,
        };
    }

    factory FolderModel.fromMap(Map<String, dynamic> map) {
        return FolderModel(
            id: map['id'] as int?,
            name: map['name'] as String,
            createdAt: map['created_at'] as String,
        );
    }
}